LEXICON = 'lexicon'
SYNTACTIC = 'syntactic'

NT = 'NonTerminal' # indicador de Tipo para símbolos NO terminales
TM = 'Terminal'    # indicador de Tipo para símbolos Terminales
EP = 'Epsilon'    # indicador de Tipo para el símbolo vacio

# SYNTACTIC CONTROL SYMBOLS CONSTANTS
EOC = '¬'
STACKBOTTOM = '∇'

# CODE GENERATOR STATUS CONSTANTS
PSTATUS0 = 'status0'
PSTATUS1 = 'status1'
PSTATUS2 = 'status2'
PSTATUS5 = 'status5'
# CODE GENERATOR IDENTATION CONSTANTS
TAB = '    '
TAB2 = '        ' # X2
TAB3 = '            ' # X3
NL = '\n'

# EXPLANATION CONSTANTS
EXPINTRODUCTION = 'introduction'
EXPFIRSTSET = 'firstset'
EXPNEXTSET = 'nextset'

# WORDS CONSTANTS
NEXTW = 'SIGUIENTE'
FIRSTW = 'PRIMERO'

EXPTITLE1 = "¿Cómo obtener el conjunto SELECCIÓN?"
EXPTITLE2 = "¿Cómo obtener el conjunto PRIMERO?"
EXPTITLE3 = "¿Cómo obtener el conjunto SIGUIENTE?"

# LEXICAL MODULE CONSTANTS
CONVERTIONDIC = {
    '.': '\.',
    '-': '\-',
    '+' : '\+',
    '*' : '\*',
    '(' : '\(',
    ')' : '\)',
    '{' : '\{',
    '}' : '\}',
    '^' : '\^',
    '|' : '\|',
}

# SYNTACTIC VALIDATION CODES
GV_OK = 0
GV_DEATH_ERROR = 1
GV_UNUSEDNT_ERROR = 2
GV_UNREACHABLE_ERROR = 3
GV_ALIVE_EXECUTION_ERROR = 4
GV_REACH_EXECUTION_ERROR = 5
GV_AMBIGUOUS_ERROR = 6
GV_AMBIGUOUS_EXECUTION_ERROR = 7
GV_1STANALISYS_EXECUTION_ERROR = 8
GV_2NDANALISYS_EXECUTION_ERROR = 9
GV_3RDANALISYS_EXECUTION_ERROR = 10
GV_4THANALISYS_EXECUTION_ERROR = 11
GV_5THANALISYS_EXECUTION_ERROR = 12
GV_6THANALISYS_EXECUTION_ERROR = 13
GV_7THANALISYS_EXECUTION_ERROR = 14
GV_8THANALISYS_EXECUTION_ERROR = 15
GV_9THANALISYS_EXECUTION_ERROR = 16
GV_10THANALISYS_EXECUTION_ERROR = 17
GV_0NT_SYMBOLS = 27
GV_WARSHALL_EXECUTION_ERROR = 18
GV_DOTOPERATION_EXECUTION_ERROR = 19
GV_SELECTIONMX_EXECUTION_ERROR = 20

LX_EXECUTION_ERROR = f'22 {NL}Error en definición de Tokens'
SX_EXECUTION_ERROR = f'23 {NL}Posible error en definición de Producción'

#CONTROL MATRIX CONSTANTS
CM_INITIAL_ERROR_VALUE = -1
CM_AMBIGUOUS = -2
CM_POP_ADVANCE = -3
CM_ACCEPTED = -5